const state={view:'dashboard',news:[{id:1,date:'2026-09-01',cat:'重要公告',title:'115年度全國高級中等學校圖書館輔導團研習開放報名',url:'',status:'已發布'},{id:2,date:'2026-08-28',cat:'研習活動',title:'AI時代圖書館創新應用研習－中區場次資訊',url:'',status:'已發布'}],events:[{id:1,region:'中區',date:'2026-09-04',title:'中區圖書館輔導團研習',place:'國立中興大學圖書館6樓會議廳'},{id:2,region:'北區',date:'2026-09-11',title:'北區圖書館輔導團研習',place:'國立陽明交通大學浩然圖書資訊中心B1國際會議廳'},{id:3,region:'南區',date:'2026-09-22',title:'南區圖書館輔導團研習',place:'國立成功大學成功校區圖書館總館B1會議廳'}]};
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}
function setView(name){state.view=name;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent=({dashboard:'總覽',news:'最新消息管理',events:'活動研習管理',resources:'資源中心',gallery:'活動成果',links:'相關連結',users:'帳號與權限',logs:'操作紀錄',settings:'網站設定'})[name]||'後台管理'; if(innerWidth<821)$('#sidebar').classList.remove('open')}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#mobileToggle')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
function renderNews(){const tb=$('#newsTableBody');if(!tb)return;tb.innerHTML=state.news.map(n=>`<tr><td>${n.date}</td><td><span class="badge ${n.cat==='重要公告'?'important':''}">${n.cat}</span></td><td>${n.title}</td><td>${n.status}</td><td><div class="row-actions"><button class="icon-action" data-edit-news="${n.id}">編輯</button><button class="icon-action" data-delete-news="${n.id}">刪除</button></div></td></tr>`).join('')}
function renderEvents(){const tb=$('#eventTableBody');if(!tb)return;tb.innerHTML=state.events.map(e=>`<tr><td>${e.region}</td><td>${e.date}</td><td>${e.title}</td><td>${e.place}</td><td><div class="row-actions"><button class="icon-action" data-edit-event="${e.id}">編輯</button></div></td></tr>`).join('')}
$('#newsForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.news.unshift({id:Date.now(),date:f.get('date'),cat:f.get('cat'),title:f.get('title'),url:f.get('url'),status:f.get('draft')?'草稿':'已發布'});renderNews();e.currentTarget.reset();toast('公告已加入目前工作階段');setView('news')});
$('#eventForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.events.push({id:Date.now(),region:f.get('region'),date:f.get('date'),title:f.get('title'),place:f.get('place')});renderEvents();e.currentTarget.reset();toast('活動已加入目前工作階段');setView('events')});
document.addEventListener('click',e=>{const del=e.target.closest('[data-delete-news]');if(del){state.news=state.news.filter(n=>n.id!==Number(del.dataset.deleteNews));renderNews();toast('已移除公告');}});
$$('[data-save-demo]').forEach(b=>b.addEventListener('click',()=>toast('已儲存介面設定（展示模式）')));
renderNews();renderEvents();
