(()=>{
'use strict';
if(window.__adminReorderLoaded)return;window.__adminReorderLoaded=true;
const configs=[
 {key:'news',tbody:'newsTableBody',edit:'news',pinned:true,label:'公告'},
 {key:'events',tbody:'eventTableBody',edit:'event',pinned:false,label:'活動'},
 {key:'resources',tbody:'resourceTableBody',edit:'resource',pinned:false,label:'資源'},
 {key:'links',tbody:'linkTableBody',edit:'link',pinned:false,label:'連結'}
];
let dragInfo=null,applying=false;
const getItem=(cfg,id)=>Array.isArray(state?.[cfg.key])?state[cfg.key].find(x=>Number(x.id)===Number(id)):null;
function normalItems(cfg){const arr=Array.isArray(state?.[cfg.key])?state[cfg.key]:[];return arr.filter(x=>!(cfg.pinned&&x.pin)).sort((a,b)=>(Number(a.order)||999999)-(Number(b.order)||999999));}
function initializeOrders(){let changed=false;configs.forEach(cfg=>{const normals=(state[cfg.key]||[]).filter(x=>!(cfg.pinned&&x.pin));normals.forEach((x,i)=>{if(!Number.isFinite(Number(x.order))||Number(x.order)<=0){x.order=i+1;changed=true}});if(cfg.key==='links'){normals.sort((a,b)=>(Number(a.order)||999999)-(Number(b.order)||999999));normals.forEach((x,i)=>{if(Number(x.order)!==i+1){x.order=i+1;changed=true}})}});if(changed)persist()}
function saveOrder(cfg,orderedIds){const arr=state[cfg.key]||[];const pinned=cfg.pinned?arr.filter(x=>x.pin):[];const normals=arr.filter(x=>!(cfg.pinned&&x.pin));const byId=new Map(normals.map(x=>[Number(x.id),x]));const ordered=[];orderedIds.forEach(id=>{const x=byId.get(Number(id));if(x){ordered.push(x);byId.delete(Number(id))}});for(const x of normals){if(byId.has(Number(x.id))){ordered.push(x);byId.delete(Number(x.id))}}ordered.forEach((x,i)=>x.order=i+1);state[cfg.key]=cfg.pinned?[...pinned,...ordered]:ordered;if(typeof addLog==='function')addLog(`調整${cfg.label}清單排序`);persist();if(typeof renderAll==='function')renderAll();if(typeof toast==='function')toast('排序已自動儲存')}
function move(cfg,id,dir){const ordered=normalItems(cfg).map(x=>Number(x.id));const i=ordered.indexOf(Number(id));if(i<0)return;const j=i+dir;if(j<0||j>=ordered.length)return;[ordered[i],ordered[j]]=[ordered[j],ordered[i]];saveOrder(cfg,ordered)}
function dragMove(cfg,sourceId,targetId,before){const ordered=normalItems(cfg).map(x=>Number(x.id));const from=ordered.indexOf(Number(sourceId)),to0=ordered.indexOf(Number(targetId));if(from<0||to0<0||from===to0)return;ordered.splice(from,1);let to=ordered.indexOf(Number(targetId));if(!before)to+=1;ordered.splice(to,0,Number(sourceId));saveOrder(cfg,ordered)}
function rowId(cfg,row){const b=row.querySelector(`[data-edit-${cfg.edit}]`);return b?Number(b.getAttribute(`data-edit-${cfg.edit}`)):0}
function applyDomOrder(cfg){const tbody=document.getElementById(cfg.tbody);if(!tbody||applying)return;const rows=[...tbody.querySelectorAll('tr')];if(!rows.length)return;const items=state[cfg.key]||[];const rank=new Map();let p=0;items.filter(x=>cfg.pinned&&x.pin).forEach(x=>rank.set(Number(x.id),p++));normalItems(cfg).forEach(x=>rank.set(Number(x.id),10000+(Number(x.order)||999999)));applying=true;rows.sort((a,b)=>(rank.get(rowId(cfg,a))??999999)-(rank.get(rowId(cfg,b))??999999)).forEach(r=>tbody.appendChild(r));applying=false}
function enhance(cfg){const tbody=document.getElementById(cfg.tbody);if(!tbody)return;applyDomOrder(cfg);[...tbody.querySelectorAll('tr')].forEach(row=>{const id=rowId(cfg,row);if(!id)return;const item=getItem(cfg,id);const pinned=!!(cfg.pinned&&item?.pin);row.dataset.sortId=id;row.classList.toggle('sort-pinned-row',pinned);row.draggable=!pinned;const actionCell=row.lastElementChild;if(!actionCell)return;let tools=actionCell.querySelector('.sort-tools');if(!tools){tools=document.createElement('div');tools.className='sort-tools';actionCell.prepend(tools)}tools.innerHTML=pinned?'<span class="sort-lock">📌 置頂固定</span>':`<button type="button" class="sort-grip" title="拖曳調整順序" aria-label="拖曳調整順序">⋮⋮</button><button type="button" class="sort-arrow" data-sort-up="${id}" title="上移" aria-label="上移">↑</button><button type="button" class="sort-arrow" data-sort-down="${id}" title="下移" aria-label="下移">↓</button>`;if(row.dataset.sortBound==='1')return;row.dataset.sortBound='1';row.addEventListener('dragstart',e=>{if(pinned){e.preventDefault();return}dragInfo={cfg,sourceId:id};row.classList.add('is-dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(id))});row.addEventListener('dragover',e=>{if(!dragInfo||dragInfo.cfg.key!==cfg.key||pinned)return;e.preventDefault();const r=row.getBoundingClientRect();row.classList.toggle('drop-after',e.clientY>r.top+r.height/2);row.classList.toggle('drop-before',e.clientY<=r.top+r.height/2)});row.addEventListener('dragleave',()=>row.classList.remove('drop-before','drop-after'));row.addEventListener('drop',e=>{if(!dragInfo||dragInfo.cfg.key!==cfg.key||pinned)return;e.preventDefault();const before=row.classList.contains('drop-before');const source=dragInfo.sourceId;row.classList.remove('drop-before','drop-after');dragMove(cfg,source,id,before)});row.addEventListener('dragend',()=>{dragInfo=null;document.querySelectorAll('.is-dragging,.drop-before,.drop-after').forEach(el=>el.classList.remove('is-dragging','drop-before','drop-after'))})})}
function enhanceAll(){configs.forEach(enhance)}
document.addEventListener('click',e=>{for(const cfg of configs){const up=e.target.closest('[data-sort-up]');if(up){move(cfg,Number(up.dataset.sortUp),-1);return}const down=e.target.closest('[data-sort-down]');if(down){move(cfg,Number(down.dataset.sortDown),1);return}}});
function addHelp(){configs.forEach(cfg=>{const tbody=document.getElementById(cfg.tbody);const panel=tbody?.closest('.panel');const head=panel?.querySelector('.panel-head');if(!head||head.querySelector('.sort-help'))return;const note=document.createElement('span');note.className='sort-help';note.textContent=cfg.pinned?'📌 置頂固定，其餘可拖曳或用 ↑↓ 排序':'拖曳列或使用 ↑↓ 調整，會自動儲存';head.appendChild(note)})}
function init(){if(typeof state==='undefined'||typeof persist!=='function')return;initializeOrders();enhanceAll();addHelp();const obs=new MutationObserver(()=>{if(applying)return;requestAnimationFrame(enhanceAll)});configs.forEach(cfg=>{const t=document.getElementById(cfg.tbody);if(t)obs.observe(t,{childList:true,subtree:false})})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,250));else setTimeout(init,250);
})();