window.LibraryGuidanceCloudConfig={
  firebase:{
    apiKey:"AIzaSyBhi8k-Fo0jI24LBAq_fmtNmkvZZx5J2JM",
    authDomain:"library-guidance-group.firebaseapp.com",
    projectId:"library-guidance-group",
    storageBucket:"library-guidance-group.firebasestorage.app",
    messagingSenderId:"1011777526571",
    appId:"1:1011777526571:web:e5e76bfdfde1bec45d8836e"
  },
  githubMedia:{
    appsScriptUrl:"https://script.google.com/macros/s/AKfycbx0ps5rtz4XR5nmdh-MBwRxMDzr7Y7fjv1ILCcpmTTXAD_Qge71-lTbaW2dCc8ofWQ_Vg/exec"
  },
  r2:{
    workerUrl:"",
    publicBaseUrl:""
  }
};
